//get item constants
const GET_ITEM_REQUEST = "GET_ITEM_REQUEST";
const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
const GET_ITEM_FAIL = "GET_ITEM_FAIL";

//get user item constants
const GET_USER_ITEM_REQUEST = "GET_USER_ITEM_REQUEST";
const GET_USER_ITEM_SUCCESS = "GET_USER_ITEM_SUCCESS";
const GET_USER_ITEM_FAIL = "GET_USER_ITEM_FAIL";

//get item  per type constants
const GET_LATEST_ITEM_PER_TYPE_REQUEST = "GET_LATEST_ITEM_PER_TYPE_REQUEST";
const GET_LATEST_ITEM_PER_TYPE_SUCCESS = "GET_LATEST_ITEM_PER_TYPE_SUCCESS";
const GET_LATEST_ITEM_PER_TYPE_FAIL = "GET_LATEST_ITEM_PER_TYPE_FAIL";

//get all items constants
const GET_ALL_ITEMS_REQUEST = "GET_ALL_ITEMS_REQUEST";
const GET_ALL_ITEMS_SUCCESS = "GET_ALL_ITEMS_SUCCESS";
const GET_ALL_ITEMS_FAIL = "GET_ALL_ITEMS_FAIL";

//search item constants
const SEARCH_ITEM_REQUEST = "SEARCH_ITEM_REQUEST";
const SEARCH_ITEM_SUCCESS = "SEARCH_ITEM_SUCCESS";
const SEARCH_ITEM_FAIL = "SEARCH_ITEM_FAIL";

//search items constants
const SEARCH_ITEMS_REQUEST = "SEARCH_ITEMS_REQUEST";
const SEARCH_ITEMS_SUCCESS = "SEARCH_ITEMS_SUCCESS";
const SEARCH_ITEMS_FAIL = "SEARCH_ITEMS_FAIL";

//add items constants
const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST";
const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
const ADD_ITEM_FAIL = "ADD_ITEM_FAIL";

//like item constants
const LIKE_ITEM_REQUEST = "LIKE_ITEM_REQUEST";
const LIKE_ITEM_SUCCESS = "LIKE_ITEM_SUCCESS";
const LIKE_ITEM_FAIL = "LIKE_ITEM_FAIL";

//get liked item constants
const GET_LIKE_ITEM_REQUEST = "GET_LIKE_ITEM_REQUEST";
const GET_LIKE_ITEM_SUCCESS = "GET_LIKE_ITEM_SUCCESS";
const GET_LIKE_ITEM_FAIL = "GET_LIKE_ITEM_FAIL";

//update item constants
const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
const UPDATE_ITEM_FAIL = "UPDATE_ITEM_FAIL";

//DELETE item constants
const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";

export {
  GET_ITEM_FAIL,
  GET_ITEM_REQUEST,
  GET_ITEM_SUCCESS,
  GET_USER_ITEM_FAIL,
  GET_USER_ITEM_REQUEST,
  GET_USER_ITEM_SUCCESS,
  GET_ALL_ITEMS_FAIL,
  GET_ALL_ITEMS_REQUEST,
  GET_ALL_ITEMS_SUCCESS,
  GET_LATEST_ITEM_PER_TYPE_FAIL,
  GET_LATEST_ITEM_PER_TYPE_REQUEST,
  GET_LATEST_ITEM_PER_TYPE_SUCCESS,
  SEARCH_ITEM_FAIL,
  SEARCH_ITEM_REQUEST,
  SEARCH_ITEM_SUCCESS,
  SEARCH_ITEMS_FAIL,
  SEARCH_ITEMS_REQUEST,
  SEARCH_ITEMS_SUCCESS,
  ADD_ITEM_FAIL,
  ADD_ITEM_REQUEST,
  ADD_ITEM_SUCCESS,
  LIKE_ITEM_FAIL,
  LIKE_ITEM_REQUEST,
  LIKE_ITEM_SUCCESS,
  GET_LIKE_ITEM_FAIL,
  GET_LIKE_ITEM_REQUEST,
  GET_LIKE_ITEM_SUCCESS,
  UPDATE_ITEM_FAIL,
  UPDATE_ITEM_REQUEST,
  UPDATE_ITEM_SUCCESS,
  DELETE_ITEM_FAIL,
  DELETE_ITEM_REQUEST,
  DELETE_ITEM_SUCCESS,
};
