
//get PAYEMENT constants
const GET_PAYEMENT_REQUEST = "GET_PAYEMENT_REQUEST"; 
const GET_PAYEMENT_SUCCESS = "GET_PAYEMENT_SUCCESS"; 
const GET_PAYEMENT_FAIL    = "GET_PAYEMENT_FAIL";


//get all PAYEMENTs constants
const GET_ALL_PAYEMENTS_REQUEST = "GET_ALL_PAYEMENTS_REQUEST"; 
const GET_ALL_PAYEMENTS_SUCCESS = "GET_ALL_PAYEMENTS_SUCCESS"; 
const GET_ALL_PAYEMENTS_FAIL    = "GET_ALL_PAYEMENTS_FAIL"; 

//add PAYEMENTs constants
const ADD_PAYEMENT_REQUEST = "ADD_PAYEMENT_REQUEST"; 
const ADD_PAYEMENT_SUCCESS = "ADD_PAYEMENT_SUCCESS"; 
const ADD_PAYEMENT_FAIL    = "ADD_PAYEMENT_FAIL"; 


//update PAYEMENT constants
const UPDATE_PAYEMENT_REQUEST = "UPDATE_PAYEMENT_REQUEST"; 
const UPDATE_PAYEMENT_SUCCESS = "UPDATE_PAYEMENT_SUCCESS"; 
const UPDATE_PAYEMENT_FAIL    = "UPDATE_PAYEMENT_FAIL"; 


//DELETE PAYEMENT constants
const DELETE_PAYEMENT_REQUEST = "DELETE_PAYEMENT_REQUEST"; 
const DELETE_PAYEMENT_SUCCESS = "DELETE_PAYEMENT_SUCCESS"; 
const DELETE_PAYEMENT_FAIL    = "DELETE_PAYEMENT_FAIL"; 

export {
    GET_PAYEMENT_FAIL,GET_PAYEMENT_REQUEST,GET_PAYEMENT_SUCCESS,
    GET_ALL_PAYEMENTS_FAIL,GET_ALL_PAYEMENTS_REQUEST,GET_ALL_PAYEMENTS_SUCCESS,
    ADD_PAYEMENT_FAIL,ADD_PAYEMENT_REQUEST,ADD_PAYEMENT_SUCCESS,
    UPDATE_PAYEMENT_FAIL,UPDATE_PAYEMENT_REQUEST,UPDATE_PAYEMENT_SUCCESS,
    DELETE_PAYEMENT_FAIL,DELETE_PAYEMENT_REQUEST,DELETE_PAYEMENT_SUCCESS
}