
//get REQUEST constants
const GET_REQUEST_REQUEST = "GET_REQUEST_REQUEST"; 
const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS"; 
const GET_REQUEST_FAIL    = "GET_REQUEST_FAIL";


//get all REQUESTs constants
const GET_ALL_REQUESTS_REQUEST = "GET_ALL_REQUESTS_REQUEST"; 
const GET_ALL_REQUESTS_SUCCESS = "GET_ALL_REQUESTS_SUCCESS"; 
const GET_ALL_REQUESTS_FAIL    = "GET_ALL_REQUESTS_FAIL"; 

//add REQUESTs constants
const ADD_REQUEST_REQUEST = "ADD_REQUEST_REQUEST"; 
const ADD_REQUEST_SUCCESS = "ADD_REQUEST_SUCCESS"; 
const ADD_REQUEST_FAIL    = "ADD_REQUEST_FAIL"; 


//update REQUEST constants
const UPDATE_REQUEST_REQUEST = "UPDATE_REQUEST_REQUEST"; 
const UPDATE_REQUEST_SUCCESS = "UPDATE_REQUEST_SUCCESS"; 
const UPDATE_REQUEST_FAIL    = "UPDATE_REQUEST_FAIL"; 


//DELETE REQUEST constants
const DELETE_REQUEST_REQUEST = "DELETE_REQUEST_REQUEST"; 
const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS"; 
const DELETE_REQUEST_FAIL    = "DELETE_REQUEST_FAIL"; 

export {
    GET_REQUEST_FAIL,GET_REQUEST_REQUEST,GET_REQUEST_SUCCESS,
    GET_ALL_REQUESTS_FAIL,GET_ALL_REQUESTS_REQUEST,GET_ALL_REQUESTS_SUCCESS,
    ADD_REQUEST_FAIL,ADD_REQUEST_REQUEST,ADD_REQUEST_SUCCESS,
    UPDATE_REQUEST_FAIL,UPDATE_REQUEST_REQUEST,UPDATE_REQUEST_SUCCESS,
    DELETE_REQUEST_FAIL,DELETE_REQUEST_REQUEST,DELETE_REQUEST_SUCCESS
}