
//get SUB constants
const GET_SUB_REQUEST = "GET_SUB_REQUEST"; 
const GET_SUB_SUCCESS = "GET_SUB_SUCCESS"; 
const GET_SUB_FAIL    = "GET_SUB_FAIL";


//get all SUBs constants
const GET_ALL_SUBS_REQUEST = "GET_ALL_SUBS_REQUEST"; 
const GET_ALL_SUBS_SUCCESS = "GET_ALL_SUBS_SUCCESS"; 
const GET_ALL_SUBS_FAIL    = "GET_ALL_SUBS_FAIL"; 

//add SUBs constants
const ADD_SUB_REQUEST = "ADD_SUB_REQUEST"; 
const ADD_SUB_SUCCESS = "ADD_SUB_SUCCESS"; 
const ADD_SUB_FAIL    = "ADD_SUB_FAIL"; 


//update SUB constants
const UPDATE_SUB_REQUEST = "UPDATE_SUB_REQUEST"; 
const UPDATE_SUB_SUCCESS = "UPDATE_SUB_SUCCESS"; 
const UPDATE_SUB_FAIL    = "UPDATE_SUB_FAIL"; 


//DELETE SUB constants
const DELETE_SUB_REQUEST = "DELETE_SUB_REQUEST"; 
const DELETE_SUB_SUCCESS = "DELETE_SUB_SUCCESS"; 
const DELETE_SUB_FAIL    = "DELETE_SUB_FAIL"; 

export {
    GET_SUB_FAIL,GET_SUB_REQUEST,GET_SUB_SUCCESS,
    GET_ALL_SUBS_FAIL,GET_ALL_SUBS_REQUEST,GET_ALL_SUBS_SUCCESS,
    ADD_SUB_FAIL,ADD_SUB_REQUEST,ADD_SUB_SUCCESS,
    UPDATE_SUB_FAIL,UPDATE_SUB_REQUEST,UPDATE_SUB_SUCCESS,
    DELETE_SUB_FAIL,DELETE_SUB_REQUEST,DELETE_SUB_SUCCESS
}