

//register constants
const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
const USER_REGISTER_FAIL    = "USER_REGISTER_FAIL"

//login constants
const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
const USER_LOGIN_FAIL   = "USER_LOGIN_FAIL"

//get users constants
const GET_USERS_REQUEST = "GET_USERS_REQUEST"
const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
const GET_USERS_FAIL    = "GET_USERS_FAIL"

//get personal info
const GET_PERSONAL_INFO_REQUEST = "GET_PERSONAL_INFO_REQUEST";
const GET_PERSONAL_INFO_SUCCESS = "GET_PERSONAL_INFO_SUCCESS";
const GET_PERSONAL_INFO_FAIL    = "GET_PERSONAL_INFO_FAIL";


//update users constants
const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
const UPDATE_USER_FAIL    = "UPDATE_USER_FAIL"


//delete users constants
const DELETE_USER_REQUEST = "GET_USER_REQUEST"
const DELETE_USER_SUCCESS = "GET_USER_SUCCESS"
const DELETE_USER_FAIL    = "GET_USER_FAIL"

//logout constants
const LOGOUT_REQUEST = "LOGOUT_REQUEST";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAIL = "LOGOUT_FAIL";



export{
    USER_LOGIN_FAIL,USER_LOGIN_REQUEST,USER_LOGIN_SUCCESS,
    USER_REGISTER_FAIL,USER_REGISTER_REQUEST,USER_REGISTER_SUCCESS,
    GET_USERS_FAIL,GET_USERS_REQUEST,GET_USERS_SUCCESS,
    GET_PERSONAL_INFO_REQUEST,GET_PERSONAL_INFO_FAIL,GET_PERSONAL_INFO_SUCCESS,
    DELETE_USER_FAIL,DELETE_USER_REQUEST,DELETE_USER_SUCCESS,
    UPDATE_USER_FAIL,UPDATE_USER_REQUEST,UPDATE_USER_SUCCESS,
    LOGOUT_FAIL,LOGOUT_REQUEST,LOGOUT_SUCCESS
}